#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
build_surfaces.py — generate the campaign surfaces from the neutral ones, and
enforce the rule the published position statement commits us to in public:

    "Both are built from the same repository, the same data and the same code.
     Neither is permitted to carry a figure the other does not — where they
     differ, they differ in voice, never in a number, a date, a citation or a
     source line."

That sentence is on STATEMENT.html, where anyone can read it and then diff the
two surfaces to check. This script is what makes it true rather than aspirational.

WHICH FILE IS CANONICAL. The neutral files — slides/index.html, STATEMENT.html —
are the source of truth and are NEVER written by this script. Campaign surfaces
are generated. If you need to change a figure, change it in the neutral file and
rebuild; if you change it in a variant, `check` will tell you.

USAGE
    python3 scripts/build_surfaces.py build    generate campaign surfaces
    python3 scripts/build_surfaces.py check    verify the invariant only
    python3 scripts/build_surfaces.py          build, then check

Exit status is non-zero on any failure, so this can gate a push.
"""

import html
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VARIANTS = os.path.join(ROOT, "profile_2026_09", "variants")
MANIFEST = os.path.join(VARIANTS, "manifest.json")

GEN_MARK = "<!-- GENERATED by scripts/build_surfaces.py — edit the neutral source, not this file -->"


# ─────────────────────────────────────────────────────────────────────────────
# Fact extraction
#
# A "fact" here is anything that carries a claim about the world: a quantity, a
# date, a statutory citation, an agency identifier, a URL. Bare prose words are
# deliberately excluded — the two surfaces are SUPPOSED to differ in prose. Only
# tokens containing a digit, plus section-symbol citations, are compared.
# ─────────────────────────────────────────────────────────────────────────────

FACT_PATTERNS = [
    r"§+\s?\d[\d.–\-]*",                       # §151.359, §§39.418-.420
    r"\b(?:RN|CN)\d{6,}\b",                          # RN112172408, CN606278281
    r"#\d{4,}",                                      # #179422, TEC report numbers
    r"\b(?:SB|HB)\s?\d+\b",                          # SB 6, HB 2127
    r"\bCh\.?\s?\d+[A-Za-z]?\b",                     # Ch. 312, Ch. 102A
    r"\bRule\s\d+\.\d+\b",                           # Rule 5.2
    r"\b\d{4}-\d{2}-\d{2}\b",                        # 2026-08-27
    r"https?://[^\s\"'<>)]+",                        # URLs
    r"\$[\d,]+(?:\.\d+)?\s?(?:million|billion|M|B)?",  # $3.8 million, $500,000
    r"\b[\d][\d,]*(?:\.\d+)?\s?%",                   # percentages
    r"\b[\d][\d,]*(?:\.\d+)?\b",                     # every remaining number
]
FACT_RE = re.compile("|".join("(?:%s)" % p for p in FACT_PATTERNS))

# A number is compared together with the word that follows it, so that
# "December 10" and "December 12" are different facts and "10 turbines" is not
# confused with "10 a month". An earlier version of this file compared bare
# numbers and filtered out everything below 16 as list-index noise; that silently
# discarded real figures — dates, turbine counts, the 3-year rollback, the 25
# tons-per-year threshold — and a deliberately corrupted date sailed through the
# check. Do not reintroduce a magnitude filter.
# Only a real unit is allowed to join the number. Attaching whatever word happens
# to follow makes prose differences look like fact differences ("60 compare" vs
# "60 talk"), which is noise, not signal.
UNITS = set("""
million billion thousand mw gw kw kwh mwh mgd gal gallon gallons acre acres
ft feet foot mile miles week weeks month months year years day days ton tons
turbine turbines parcel parcels well wells site sites county counties percent
hour hours tpy ppm megawatt megawatts gigawatt gigawatts
""".split())
TRAILING_WORD = re.compile(r"\s*([A-Za-z%][A-Za-z.%-]{0,14})")
MONTH = re.compile(
    r"(?:January|February|March|April|May|June|July|August|September|October|"
    r"November|December)$")


def visible_text(markup):
    """Strip tags, scripts, styles and comments; return decoded visible text."""
    s = re.sub(r"(?is)<(script|style)\b.*?</\1>", " ", markup)
    s = re.sub(r"(?s)<!--.*?-->", " ", s)
    s = re.sub(r"(?s)<[^>]+>", " ", s)
    return re.sub(r"\s+", " ", html.unescape(s))


def facts(markup):
    """The set of distinct world-claims in a document, each with enough context
    to be meaningful: a preceding month name where there is one, and the word
    that follows."""
    text = visible_text(markup)
    out = set()
    for m in FACT_RE.finditer(text):
        tok = re.sub(r"\s+", " ", m.group(0).strip().rstrip(".,;:"))
        if not tok:
            continue
        before = MONTH.search(text[max(0, m.start() - 12):m.start()].strip())
        after = TRAILING_WORD.match(text[m.end():m.end() + 18])
        parts = []
        if before:
            parts.append(before.group(0))
        parts.append(tok)
        if after:
            w = after.group(1).lower().rstrip(".")
            if w in UNITS or w == "%":
                parts.append(w)
        out.add(" ".join(parts))
    return out


# ─────────────────────────────────────────────────────────────────────────────
# Build
# ─────────────────────────────────────────────────────────────────────────────

SECTION_RE = '    <section class="slide" id="%s">.*?\\n    </section>'


def banner(canonical_url, kind):
    other = "the reporting version" if kind == "campaign" else "the campaign version"
    return (
        '\n  <div style="background:#f3efe6;border-bottom:1px solid #d9d2c4;'
        'padding:0.6rem 1rem;font:500 0.86rem/1.5 system-ui,sans-serif;color:#44403a">'
        '<strong>Campaign version.</strong> This page argues a case. '
        'The same research, written as a record rather than an argument, is '
        '<a href="%s" style="color:#1f2937">%s</a> — '
        'the two differ in voice and in nothing else, and that is checkable: '
        'no figure, date, citation or source line may appear in one and not the other.'
        "</div>\n" % (canonical_url, other)
    )


def build_surface(spec, errors):
    src_path = os.path.join(ROOT, spec["source"])
    out_path = os.path.join(ROOT, spec["output"])

    if os.path.abspath(src_path) == os.path.abspath(out_path):
        errors.append("%s: source and output are the same file" % spec["name"])
        return None

    with open(src_path, encoding="utf-8") as fh:
        src = fh.read()

    if spec.get("whole_file"):
        vp = os.path.join(VARIANTS, spec["whole_file"])
        if not os.path.exists(vp):
            errors.append("%s: missing variant %s" % (spec["name"], spec["whole_file"]))
            return None
        with open(vp, encoding="utf-8") as fh:
            out = fh.read()
    else:
        out = src
        for sec_id, vfile in sorted(spec.get("sections", {}).items()):
            vp = os.path.join(VARIANTS, vfile)
            if not os.path.exists(vp):
                errors.append("%s: missing variant %s" % (spec["name"], vfile))
                continue
            with open(vp, encoding="utf-8") as fh:
                replacement = fh.read().rstrip("\n")
            pat = re.compile(SECTION_RE % re.escape(sec_id), re.S)
            if len(pat.findall(out)) != 1:
                errors.append(
                    "%s: section id=%r matched %d times in %s (expected exactly 1)"
                    % (spec["name"], sec_id, len(pat.findall(out)), spec["source"])
                )
                continue
            out = pat.sub(lambda _m: replacement, out, count=1)

        for neutral_img, campaign_img in sorted(spec.get("image_swaps", {}).items()):
            target = os.path.join(os.path.dirname(src_path), campaign_img)
            if not os.path.exists(target):
                errors.append(
                    "%s: image swap target missing: %s\n"
                    "      generate it with:  cd profile_2026_09 && "
                    "RCO_VOICE=campaign Rscript regen_chart_G_2026-09.R"
                    % (spec["name"], os.path.relpath(target, ROOT))
                )
                continue
            if neutral_img not in out:
                errors.append("%s: image swap source %s not present" % (spec["name"], neutral_img))
                continue
            out = out.replace(neutral_img, campaign_img)

    for name, frag_file in sorted(spec.get("shared_blocks", {}).items()):
        fp = os.path.join(VARIANTS, frag_file)
        if not os.path.exists(fp):
            errors.append("%s: missing shared block %s" % (spec["name"], frag_file))
            continue
        with open(fp, encoding="utf-8") as fh:
            frag = fh.read().rstrip("\n")
        marker = "<!-- SHARED:%s -->" % name
        if marker not in out:
            errors.append(
                "%s: shared block %r declared but marker %s is not in the variant"
                % (spec["name"], name, marker))
            continue
        out = out.replace(marker, frag)

    # banner + generation marker, inserted after <body> where there is one
    b = banner(spec.get("canonical_url", "index.html"), "campaign")
    if "<body>" in out:
        out = out.replace("<body>", "<body>\n" + GEN_MARK + b, 1)
    else:
        out = GEN_MARK + "\n" + out

    return out_path, out


def cmd_build():
    with open(MANIFEST, encoding="utf-8") as fh:
        man = json.load(fh)

    errors, written = [], []
    for spec in man["surfaces"]:
        res = build_surface(spec, errors)
        if res is None:
            continue
        out_path, out = res
        with open(out_path, "w", encoding="utf-8") as fh:
            fh.write(out)
        written.append((spec["name"], os.path.relpath(out_path, ROOT), len(out)))

    for name, rel, n in written:
        print("  built  %-22s %-28s %8d bytes" % (name, rel, n))
    for e in errors:
        print("  ERROR  " + e)
    return 1 if errors else 0


# ─────────────────────────────────────────────────────────────────────────────
# Check
# ─────────────────────────────────────────────────────────────────────────────

def cmd_check():
    with open(MANIFEST, encoding="utf-8") as fh:
        man = json.load(fh)
    global_allowed = set(man.get("fact_exceptions", []))

    failures = 0
    for spec in man["surfaces"]:
        src_path = os.path.join(ROOT, spec["source"])
        out_path = os.path.join(ROOT, spec["output"])
        if not os.path.exists(out_path):
            print("  ERROR  %s: %s not built yet" % (spec["name"], spec["output"]))
            failures += 1
            continue

        # per-surface exceptions are a dict of token -> why it is allowed to differ
        local = spec.get("fact_exceptions", {})
        allowed = global_allowed | set(local)

        with open(src_path, encoding="utf-8") as fh:
            neutral = facts(fh.read())
        with open(out_path, encoding="utf-8") as fh:
            campaign = facts(fh.read())

        # a shared block is a matter of record, not voice: its text must appear
        # verbatim in the neutral source as well as in the generated campaign file
        for name, frag_file in sorted(spec.get("shared_blocks", {}).items()):
            fp = os.path.join(VARIANTS, frag_file)
            with open(fp, encoding="utf-8") as fh:
                frag_text = visible_text(fh.read()).strip()
            with open(src_path, encoding="utf-8") as fh:
                if frag_text not in visible_text(fh.read()):
                    print("  FAIL   %s: shared block %r has drifted from %s"
                          % (spec["name"], name, spec["source"]))
                    print("         Re-sync %s with the fragment in %s."
                          % (spec["source"], frag_file))
                    failures += 1

        only_n = sorted(neutral - campaign - allowed)
        only_c = sorted(campaign - neutral - allowed)

        if not only_n and not only_c:
            note = ("" if not local else
                    ", %d reasoned exception%s" % (len(local), "" if len(local) == 1 else "s"))
            print("  ok     %-22s %d figures, identical on both surfaces%s"
                  % (spec["name"], len(neutral), note))
            for tok in sorted(local):
                print("           except %-6s %s" % (tok, local[tok]))
            continue

        failures += 1
        print("  FAIL   %s" % spec["name"])
        if only_n:
            print("         in %s but NOT in the campaign version:" % spec["source"])
            for f in only_n:
                print("           %s" % f)
        if only_c:
            print("         in the campaign version but NOT in %s:" % spec["source"])
            for f in only_c:
                print("           %s" % f)
        print("         Fix the variant so it carries the same figures, or add an")
        print("         explicit entry with a reason to fact_exceptions in")
        print("         profile_2026_09/variants/manifest.json.")
    return 1 if failures else 0


def main():
    cmd = sys.argv[1] if len(sys.argv) > 1 else "all"
    if cmd not in ("build", "check", "all"):
        print(__doc__)
        return 2
    rc = 0
    if cmd in ("build", "all"):
        print("build:")
        rc |= cmd_build()
    if cmd in ("check", "all"):
        print("check:  a figure in one surface and not the other is a failure")
        rc |= cmd_check()
    print("\n%s" % ("FAILED" if rc else "OK — the two surfaces differ in voice only"))
    return rc


if __name__ == "__main__":
    sys.exit(main())
